export const FETCH_WEATHER_BEGIN = 'FETCH_WEATHER_BEGIN'; 
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE';

export const SHOW_WEATHER_CARD = 'SHOW_WEATHER_CARD';
export const HIDE_WEATHER_CARD = 'HIDE_WEATHER_CARD';



  