export const FETCH_WEATHER_BEGIN = 'FETCH_WEATHER_BEGIN'; 
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE';

export const SELECT_LOCATION = 'SELECT_LOCATION';
export const INVALIDATE_LOCATION = 'INVALIDATE_LOCATION'

export const REQUEST_MY_LOCATION = 'REQUEST_MY_LOCATION'
export const RECEIVE_MY_LOCATION = 'RECEIVE_MY_LOCATION'




  