export const FETCH_WEATHER_BEGIN = 'FETCH_WEATHER_BEGIN'; 
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE';

export const SELECT_LOCATION = 'SELECT_LOCATION';
export const INVALIDATE_LOCATION = 'INVALIDATE_LOCATION'

export const GET_LOCATION_BEGIN = 'GET_LOCATION_BEGIN'
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS'
export const GET_LOCATION_FAILURE = 'GET_LOCATION_FAILURE'




  